.TH mrkdwn 7

.SH NAME
md \- preview markdown files

.SH SYNOPSIS
\fBmd\fP \fIFILES\fP

.SH DESCRIPTION
Renders the given markdown file in a temporary HTML file and fires a browser displaying it.

\fB--help\fR    displays a help message and exit

\fB--version\fR displays the version number and exit

.SH BUGS
https://github.com/tallesl/node-mrkdwn/issues

.SH AUTHOR
Talles L <talleslasmar@gmail.com>
